apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Env.NAMESPACE }}
  labels:
    app: {{ .Name }}
    version: {{ .Version }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Name }}
      version: {{ .Version }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
        version: {{ .Version }}
    spec:
      containers:
      - name: {{ .Name }}
        image: {{ .Image }}
        command: [ "/app/{{ .Name }}" ]
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-staged
  namespace: {{ .Env.NAMESPACE }}
spec:
  selector:
    app: {{ .Name }}
    version: {{ .Version }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---



apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Name }}-staged
  namespace: {{ .Env.NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "{{ .Name }}.staging.{{ .Env.ROOT_DOMAIN }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Name }}-staged
          servicePort: 3000
---
